version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb-db
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db
  # redis:
  #   image: redis
  #   container_name: redis-app
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data

  # postgres:
  #   image: postgres
  #   container_name: postgres-db
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     POSTGRES_DB: sourav
  #     POSTGRES_USER: root
  #     POSTGRES_PASSWORD: sourav
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

volumes:
  mongodb_data:
    driver: local
  redis_data:
    driver: local
  postgres_data:
    driver: local
